name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build
      env:
        HEALTH_APIS_RELEASES_NEXUS_USERNAME: ${{ secrets.HEALTH_APIS_RELEASES_NEXUS_USERNAME }}
        HEALTH_APIS_RELEASES_NEXUS_PASSWORD: ${{ secrets.HEALTH_APIS_RELEASES_NEXUS_PASSWORD }}
      run: |
        mvn -B package \
          --file pom.xml \
          --settings settings.xml \
          -Ddocker.skip=true \
          -Dhealth-apis-releases.nexus.user=$HEALTH_APIS_RELEASES_NEXUS_USERNAME \
          -Dhealth-apis-releases.nexus.passwo\rd=$HEALTH_APIS_RELEASES_NEXUS_PASSWORD
